### ISSUE TITLE
contract.isplayer is not a function

### ISSUE THREAD

**Issue by Thebks** [adrianhajdin/project_web3_battle_game#6]
I'm getting the "`contract.isplayer` is not a function" error but it's not because of the `providers.getSigner` . The error is coming from `UpdateCurrentWalletAddress` function. It shows that there is an "uncaught (in primise) object" in that function.

**Comment by Thebks** [comment]
![Screenshot from 2022-12-08 12-34-36](https://user-images.githubusercontent.com/35862695/206386582-bc0678a4-e338-4fe4-9300-2d42da9f7e5f.png)
![Screenshot from 2022-12-08 12-34-19](https://user-images.githubusercontent.com/35862695/206386616-b6bf5e10-c312-4ada-864f-95a6e8a466d6.png)

**Comment by warkingous** [comment]
> I'm getting the "`contract.isplayer` is not a function" error but it's not because of the `providers.getSigner` . The error is coming from `UpdateCurrentWalletAddress` function. It shows that there is an "uncaught (in primise) object" in that function.

use 'eth_accounts' instead of 'eth_requestAccounts'

**Comment by cforcross** [comment]
> I'm getting the "`contract.isplayer` is not a function" error but it's not because of the `providers.getSigner` . The error is coming from `UpdateCurrentWalletAddress` function. It shows that there is an "uncaught (in primise) object" in that function.

@Thebks any luck figuring this out?

**Comment by cforcross** [comment]
> > I'm getting the "`contract.isplayer` is not a function" error but it's not because of the `providers.getSigner` . The error is coming from `UpdateCurrentWalletAddress` function. It shows that there is an "uncaught (in primise) object" in that function.
> 
> use 'eth_accounts' instead of 'eth_requestAccounts'

didn't solve the error on my end. copied and pasted the exact code from the repo but the error persisted

**Comment by Thebks** [comment]
Yes actually I somehow got rid of it and the problem had something to do with my wallet connection. Make sure you don't have a connection problem and every time you make changes in your code you have to refresh your browser and sign in to your wallet again. 

could you also share your code so I can see if you don't mind?

**Comment by Thebks** [comment]
Make sure you added the private key in the .env file and then add the contract address once you compile it in the `client/src/contract/index.js` directory like this `export const ADDRESS = '0x0000000000000000000000000000';`  

If you have copied the exact code then I think the problem is with the wallet connection so do check that.
